BEGIN;
set client_encoding to latin1;
CREATE EXTENSION tablefunc;
CREATE TABLE people ( id int NOT NULL PRIMARY KEY );
CREATE TABLE part97 ( callsign varchar(10) primary key, name varchar(200) not null, symbol int not null default 0 );
CREATE TABLE datatypes ( typeid int PRIMARY KEY, name varchar(12) unique, label varchar(32), exact boolean default false, enum boolean default false );
INSERT INTO datatypes VALUES ( 0, 'status', 'Status', 'f', 't' );
INSERT INTO datatypes VALUES ( 1, 'message', 'Message', 'f', 'f' );
CREATE TABLE defaults ( callsign char(12) primary key, defsearch varchar(12) references datatypes(name), defupdate varchar(12) );
CREATE TABLE persondata ( personid int references people(id) NOT NULL, datatype int references datatypes(typeid) NOT NULL, value varchar(512), PRIMARY KEY (personid,datatype) );
CREATE TABLE quickmesg ( text varchar(255) );
CREATE TABLE updatesequence ( personid int references people(id) NOT NULL, timestamp int NOT NULL, source varchar(35) NOT NULL, datatype int REFERENCES datatypes(typeid), value varchar(255) NOT NULL );
CREATE TABLE sessions ( sessionid character varying(32) NOT NULL, callsign character varying(25) NOT NULL, "timestamp" bigint, symbol integer DEFAULT 0 NOT NULL, tactical character varying(64));
CREATE TABLE messages ( timestamp int NOT NULL, callsign varchar(25) NOT NULL, message varchar(255) NOT NULL, dest varchar(25) NOT NULL );
CREATE TABLE pidmap ( pid int, callsign varchar(12) );
INSERT INTO people VALUES ( 0 );
CREATE TABLE async ( jobid serial, filename varchar(64) not null, callsign varchar(8) not null, searchtype int REFERENCES datatypes(typeid), updatetype int, data varchar(255) not null, state int DEFAULT 0, progress int DEFAULT 0, timestamp int NOT NULL);
-- setval('async_jobid_seq', 1);
INSERT INTO messages VALUES ( extract(epoch from now() )::integer, 'SysOp', 'Database Setup Complete', 'all' );
CREATE TABLE enumtypes ( id int not null, datatype int not null, value varchar not null, constraint datatype_fk foreign key (datatype) references datatypes(typeid) );
CREATE TABLE race ( raceid int not null primary key, head real check (head >= 0) check (head < 27), tail real check (tail <= head) check ( tail < 27 )  );
copy "part97" from '/tmp/trivnet-fcc.out';
COMMIT;
