stages:
  - preflight
  - assets
  - package
  - deploy

php-lint:
  stage: preflight
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  tags:
    - docker
  script:
    - find ./ -name \*.php -exec php -l '{}' \;

get-fcc-db:
  stage: assets
  tags:
    - docker
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  script:
    - mkdir /tmp/trivnet
    - curl -o /tmp/trivnet/l_amat.zip http://storage.corbettdigital.net/l_amat.zip
    - unzip -d /tmp/trivnet/ /tmp/trivnet/l_amat.zip
    - php util/fcc-util.php /tmp/trivnet/
  artifacts:
    paths:
      - /tmp/trivnet-fcc.out

rpmbuild:
  stage: package
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  tags:
    - docker
  script:
    - for i in SOURCES BUILD BUILDROOT SPECS RPMS; do mkdir -p rpmbuild/${i}; done
    - rsync -rv src/ rpmbuild/BUILD/trivnet/
    - rsync -rv util/ rpmbuild/BUILD/util/
    - mv httpd.conf rpmbuild/SOURCES/
    - mv trivnet.spec rpmbuild/SPECS/
    - rpmbuild --define "_topdir `pwd`/rpmbuild/" -bb rpmbuild/SPECS/trivnet.spec
  artifacts:
    paths:
      - rpmbuild/RPMS/
  dependencies:
    - get-fcc-db

deploy-stage:
  stage: deploy
  tags:
    - trivnet-stage
  dependencies:
    - rpmbuild
  script:
    - ls -alR
    - sudo yum localinstall rpmbuild/RPMS/x86_64/trivnet*.rpm
