stages:
  - preflight
  - assets
  - deploy

php-lint:
  stage: preflight
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  tags:
    - docker
  script:
    - find ./ -name \*.php -print0 | xargs -I '{}' -n1 -0 php -l '{}'
    - find ./ -name \*.inc -print0 | xargs -I '{}' -n1 -0 php -l '{}'

get-fcc-db:
  stage: assets
  tags:
    - docker
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  script:
    - mkdir fcc
    - curl -s -o fcc/l_amat.zip http://storage.corbettdigital.net/l_amat.zip
    - unzip -d fcc/ fcc/l_amat.zip
    - mv `php util/fcc-util.php fcc/` ./fcc/
  artifacts:
    paths:
      - fcc/trivnet-fcc.out

deploy-stage:
  stage: deploy
  tags:
    - docker-shell
  only:
    - master  
  variables:
    GIT_STRATEGY: clone
  dependencies:
    - get-fcc-db
  environment:
    name: Stage
    url: http://docker.corbettdigital.net:8080/
  script:
    - mv fcc/trivnet-fcc.out docker/postgres/
    - docker compose down
    - chown gitlab-runner -R src/
    - chmod a+rX -R docker/
    - echo -e "<?php\n\$sha=\"${CI_COMMIT_SHA}\";\n?>\n" > src/include/sha.inc
    - docker compose up -d
    - docker save trivnetphp -o trivnetphp.tar
  artifacts:
    paths:
      - trivnetphp.tar

stop-stage:
  stage: deploy
  tags:
    - docker-shell
  variables:
    GIT_STRATEGY: none
  only:
    - master
  when: manual
  environment:
    name: Stage
    action: stop
  script:
    - docker compose down

deploy-prod:
  stage: deploy
  when: manual
  tags:
    - trivnet-prod
  only:
    - master  
  variables:
    GIT_STRATEGY: clone
  dependencies:
    - get-fcc-db
    - deploy-stage
  script:
    - docker load < trivnetphp.tar && rm -f trivnetphp.tar
    - mv fcc/trivnet-fcc.out docker/postgres/
    - docker compose down
    - chown gitlab-runner -R src/
    - chmod a+rX -R docker/
    - echo -e "<?php\n\$sha=\"${CI_COMMIT_SHA}\";\n?>\n" > src/include/sha.inc
    - docker compose up -d
  environment:
    name: Production
    url: https://trivnet.corbettdigital.net/trivnet/
