stages:
  - preflight
  - package
  - deploy

php-lint:
  stage: preflight
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  tags:
    - docker
  script:
    - find ./ -name \*.php -exec php -l '{}' \;

rpmbuild:
  stage: package
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  tags:
    - docker
  script:
    - for i in SOURCES BUILD BUILDROOT SPECS RPMS; do mkdir -p rpmbuild/${i}; done
    - rsync -rv src/ rpmbuild/BUILD/trivnet/
    - rsync -rv util/ rpmbuild/BUILD/util/
    - mv httpd.conf rpmbuild/SOURCES/
    - mv trivnet.spec rpmbuild/SPECS/
    - rpmbuild --define "_topdir `pwd`/rpmbuild/" -bb rpmbuild/SPECS/trivnet.spec
  artifacts:
    paths:
      - rpmbuild/RPMS/

deploy-stage:
  stage: deploy
  tags:
    - trivnet-stage
  dependencies:
    - rpmbuild
  script:
    - ls -alR
    - sudo yum localinstall rpmbuild/RPMS/x86_64/trivnet*.rpm
