stages:
  - preflight
  - assets
  - deploy

php-lint:
  stage: preflight
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  tags:
    - docker
  script:
    - find ./ -name \*.php -print0 | xargs -I '{}' -n1 -0 php -l '{}'
    - find ./ -name \*.inc -print0 | xargs -I '{}' -n1 -0 php -l '{}'

get-fcc-db:
  stage: assets
  tags:
    - docker
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  script:
    - mkdir fcc
    - curl -s -o fcc/l_amat.zip http://storage.corbettdigital.net/l_amat.zip
    - unzip -d fcc/ fcc/l_amat.zip
    - mv `php util/fcc-util.php fcc/` ./fcc/
  artifacts:
    paths:
      - fcc/trivnet-fcc.out

create-web-container:
  stage: assets
  tags:
    - docker-shell
  only:
    - master  
  variables:
    GIT_STRATEGY: clone
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - /bin/docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - mkdir src/js/ src/css/
    - curl -o src/js/jquery.js -L https://code.jquery.com/jquery-3.7.0.min.js
    - curl -LO https://jqueryui.com/resources/download/jquery-ui-1.13.2.zip && unzip jquery-ui-1.13.2.zip
    - mv jquery-ui-1.13.2/jquery-ui.min.js src/js/jquery-ui.js && mv jquery-ui-1.13.2/jquery-ui.min.css src/css/jquery-ui.css
    - echo -e "<?php\n\$sha=\"${CI_COMMIT_SHA}\";\n?>\n" > src/include/sha.inc
    - docker build -t trivnetphp -f docker/web/Dockerfile . 
    - docker tag trivnetphp $IMAGE_TAG
    - docker push $IMAGE_TAG

.rpmbuild:
  stage: package
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  tags:
    - docker
  script:
    - for i in SOURCES BUILD BUILDROOT SPECS RPMS; do mkdir -p rpmbuild/${i}; done
    - rsync -rv src/ rpmbuild/BUILD/trivnet/
    - rsync -rv util/ rpmbuild/BUILD/util/
    - mv httpd.conf rpmbuild/SOURCES/
    - mv trivnet-async.service rpmbuild/SOURCES/
    - mv fcc/trivnet-fcc.out rpmbuild/SOURCES/
    - mv trivnet.spec rpmbuild/SPECS/
    - echo "SetEnv TRIVNET-SHA ${CI_COMMIT_SHA}" > rpmbuild/BUILD/trivnet/.htaccess
    - rpmbuild --define "now `date +%s`" --define "_topdir `pwd`/rpmbuild/" -bb rpmbuild/SPECS/trivnet.spec
  artifacts:
    paths:
      - rpmbuild/RPMS/
      - Dockerfile
  dependencies:
    - get-fcc-db

.deploy-stage:
  stage: deploy
  tags:
    - trivnet-stage
  variables:
    GIT_STRATEGY: none
  dependencies:
    - rpmbuild
  script:
    - sudo yum -y remove postgresql-libs trivnet trivnet-static postgresql96-libs postgresql13-libs
    - sudo rm -rf /var/lib/pgsql
    - sudo yum -y localinstall rpmbuild/RPMS/noarch/trivnet*.rpm
  after_script:
    - find ./ -name \*.rpm -delete
  environment:
    name: Stage
    url: http://172.16.104.76/trivnet/

deploy-stage:
  stage: deploy
  tags:
    - docker-shell
  only:
    - master  
  variables:
    GIT_STRATEGY: clone
  dependencies:
    - get-fcc-db
  environment:
    name: Stage
    url: http://docker.corbettdigital.net:8080/
  script:
    - mv fcc/trivnet-fcc.out docker/postgres/
    - docker compose down
    - chown gitlab-runner -R src/
    - chmod a+rX -R docker/
    - docker compose up -d

stop-stage:
  stage: deploy
  tags:
    - docker-shell
  variables:
    GIT_STRATEGY: none
  only:
    - master
  when: manual
  environment:
    name: Stage
    action: stop
  script:
    - docker compose down


.deploy-macbookair:
  stage: deploy
  tags:
    - trivnet-macbookair
  only:
    - master  
  variables:
    GIT_STRATEGY: clone
  dependencies:
    - get-fcc-db
  environment:
    name: MacBook Air
    url: http://192.168.64.2:8080/
  script:
    - mv fcc/trivnet-fcc.out docker/postgres/
    - docker-compose down
    - chown gitlab-runner -R src/
    - docker-compose up -d

.stop-macbookair:
  stage: deploy
  tags:
    - trivnet-macbookair
  variables:
    GIT_STRATEGY: none
  only:
    - master
  when: manual
  environment:
    name: MacBook Air
    action: stop
  script:
    - docker-compose down


.deploy-prod:
  stage: deploy
  when: manual
  tags:
    - trivnet-prod
  variables:
    GIT_STRATEGY: none
  dependencies:
    - rpmbuild
  script:
    - sudo yum -y localinstall rpmbuild/RPMS/noarch/trivnet*.rpm
  after_script:
    - find ./ -name \*.rpm -delete      
  environment:
    name: Production
    url: http://10.145.67.1/trivnet/
            
