stages:
  - preflight
  - assets
  - package
  - deploy

php-lint:
  stage: preflight
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  tags:
    - docker
  script:
    - find ./ -name \*.php -print0 | xargs -I '{}' -n1 -0 php -l '{}'
    - find ./ -name \*.inc -print0 | xargs -I '{}' -n1 -0 php -l '{}'

get-fcc-db:
  stage: assets
  tags:
    - docker
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  script:
    - mkdir fcc
    - curl -s -o fcc/l_amat.zip http://storage.corbettdigital.net/l_amat.zip
    - unzip -d fcc/ fcc/l_amat.zip
    - mv `php util/fcc-util.php fcc/` ./fcc/
  artifacts:
    paths:
      - fcc/trivnet-fcc.out

rpmbuild:
  stage: package
  image: dockreg.corbettdigital.net/trivnet/buildenv:master
  tags:
    - docker
  script:
    - for i in SOURCES BUILD BUILDROOT SPECS RPMS; do mkdir -p rpmbuild/${i}; done
    - rsync -rv src/ rpmbuild/BUILD/trivnet/
    - rsync -rv util/ rpmbuild/BUILD/util/
    - mv httpd.conf rpmbuild/SOURCES/
    - mv trivnet-async.service rpmbuild/SOURCES/
    - mv fcc/trivnet-fcc.out rpmbuild/SOURCES/
    - mv trivnet.spec rpmbuild/SPECS/
    - echo "SetEnv TRIVNET-SHA ${CI_COMMIT_SHA}" > rpmbuild/BUILD/trivnet/.htaccess
    - rpmbuild --define "now `date +%s`" --define "_topdir `pwd`/rpmbuild/" -bb rpmbuild/SPECS/trivnet.spec
  artifacts:
    paths:
      - rpmbuild/RPMS/
      - Dockerfile
  dependencies:
    - get-fcc-db

deploy-stage:
  stage: deploy
  tags:
    - trivnet-stage
  variables:
    GIT_STRATEGY: none
  dependencies:
    - rpmbuild
  script:
    - sudo yum -y remove postgresql-libs trivnet trivnet-static postgresql96-libs postgresql13-libs
    - sudo rm -rf /var/lib/pgsql
    - sudo yum -y localinstall rpmbuild/RPMS/noarch/trivnet*.rpm
  after_script:
    - find ./ -name \*.rpm -delete
  environment:
    name: Stage
    url: http://172.16.104.76/trivnet/

deploy-macbookair:
  stage: deploy
  dependencies:
    - rpmbuild
  tags:
    - trivnet-macbookair
  script:
    - pwd
    - find ./ -type f
    - docker build .
    - docker run -p 8080:80 
  after_script:
    - find ./ -name \*.rpm -delete
  variables:
    GIT_STRATEGY: none
  environment:
    name: UTM
    url: http://192.168.64.2:8080/trivnet/

.deploy-thin:
  stage: deploy
  tags:
    - trivnet-thin
  variables:
    GIT_STRATEGY: none
  dependencies:
    - rpmbuild
  script:
    - sudo yum -y remove postgresql-libs trivnet trivnet-static postgresql96-libs postgresql13-libs
    - sudo rm -rf /var/lib/pgsql
    - sudo yum -y localinstall rpmbuild/RPMS/noarch/trivnet*.rpm
  after_script:
    - find ./ -name \*.rpm -delete
  environment:
    name: Thin Client
    url: http://10.254.10.111/trivnet/

deploy-prod:
  stage: deploy
  when: manual
  tags:
    - trivnet-prod
  variables:
    GIT_STRATEGY: none
  dependencies:
    - rpmbuild
  script:
    - sudo yum -y localinstall rpmbuild/RPMS/noarch/trivnet*.rpm
  after_script:
    - find ./ -name \*.rpm -delete      
  environment:
    name: Production
    url: http://10.145.67.1/trivnet/
            
