services:
  web:
    image: dockreg.corbettdigital.net/trivnet/trivnet:master
    networks:
     - trivnet
    depends_on:
      - database
    volumes:
      - asyncdata:/var/www/html/jobs/
    restart: unless-stopped
    ports:
      - "8080:80"
  async:
    image: dockreg.corbettdigital.net/trivnet/trivnet:master
    command: php /var/www/html/async.php --daemon
    networks:
     - trivnet
    depends_on:
      - database
    volumes:
      - asyncdata:/var/www/html/jobs/
    restart: unless-stopped
  database:
    image: postgres:15-alpine
    networks:
     - trivnet
    restart: unless-stopped
    volumes:
      - "./docker/postgres/:/docker-entrypoint-initdb.d/"
      - pgdatadata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: trivnet
      POSTGRES_USER: trivnet
      POSTGRES_DB: trivnet
  prometheus:
    image: prom/prometheus
    networks:
     - trivnet
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - "./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"

volumes:
  asyncdata:
  pgdata:
networks:
  trivnet: