{
 "title": "TCM General Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Med Tent Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "trivnet_status{label=\"In Med Tent\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "SAG Bus Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "trivnet_status{label=~\"🚍 On SAG Bus .+\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Cumulative Statuses",
   "type": "timeseries",
   "description": "Cumulative totals of 'latching' or 'sticky' statuses.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "latching_status{job=\"trivnet\"}",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}