<?php

$cmds["tn_help"][] = "?";
$cmds["tn_help"][] = "help";

$cmds["tn_addfield"][] = "addfield";
$cmds["tn_delfield"][] = "delfield";
$cmds["tn_listfields"][] = "listfields";

$cmds["tn_search"][] = "search";

$cmds["tn_now"][] = "now";
$cmds["tn_now"][] = "date";
$cmds["tn_now"][] = "time";

$cmds["tn_details"][] = "info";
$cmds["tn_details"][] = "details";
$cmds["tn_details"][] = "show";

$cmds["tn_update"][] = "update";

$cmds["tn_tell"][] = "tell";

$cmds["tn_who"][] = "who";
$cmds["tn_who"][] = "users";
$cmds["tn_who"][] = "mheard";

$cmds["tn_whoami"][] = "whoami";
$cmds["tn_mycall"][] = "mycall";

$cmds["tn_exit"][] = "exit";
$cmds["tn_exit"][] = "quit";
$cmds["tn_exit"][] = "bye";
$cmds["tn_exit"][] = "logout";

$cmds["tn_batch"][] = "batch";

?>
